
robot_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  



arm_trajectory_controller:
  type: position_velocity_controllers/JointTrajectoryController
  joints:
     - rotation1_joint
     - shoulder1_joint 
     - shoulder2_joint 
     - rotation2_joint 
     - shoulder3_joint 
     - wrist_joint 
  publish_rate: 50

gripper_controller:
 type: gripper_controllers/PosVelGripperController
 left_joint: 'left_finger_joint'
 right_joint: 'right_finger_joint'
 goal_tolerance: 0.005
 stalled_velocity_threshold: 0.005
 stall_timeout: 1.0
 joints_vel: 0.5
 action_monitor_rate: 50


